# Generated by Django 2.0.7 on 2018-07-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='domain_url',
            field=models.CharField(default='localhost', max_length=100),
        ),
    ]
