# Generated by Django 2.0.7 on 2018-07-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0002_client_domain_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='domain_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
