# Generated by Django 2.0.7 on 2018-07-27 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_alnode'),
    ]

    operations = [
        migrations.AddField(
            model_name='alnode',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_set', to='nodes.ALNode'),
        ),
    ]
